#+title: CVMFS

CVMFS is a file system which mounts remote directories over HTTP.
CVMFS is also by many to distribute software binaries.  Once set up it
provides the simplest way to access UPS product areas provided by
Fermilab.

It has excellent documentation which needs no repeating here other
than to link:

- [[https://cernvm.cern.ch/portal/filesystem/downloads][CVMFS download instructions]]
- [[https://cernvm.cern.ch/portal/filesystem/quickstart][CVMFS quickstart]] 

Do note that CERN's ~cvmfs-release-latest_all.deb~ may choose the wrong
distribution.  If so, remove, remake and edit
~/etc/apt/sources.list.d/cernvm.list~ to use the correct distribution.
New distributions may not yet have all packages (eg, at time of
writing Ubuntu 18.04 "bionic" does not have ~cvmfs-config-default~).
Going down to the next most recent release may work.

However, for getting access to UPS product areas, here are the salient
parts:

Edit ~/etc/cvmfs/default.local~ to look something like:

#+BEGIN_EXAMPLE
# required, add more if needed.
CVMFS_REPOSITORIES=larsoft.opensciencegrid.org,uboone.opensciencegrid.org,dune.opensciencegrid.org
# requires, replace with actual proxy, or just "DIRECT" if none
CVMFS_HTTP_PROXY="http://my.local.proxy:1234;DIRECT"
# BNL Physics department users may use
# CVMFS_HTTP_PROXY="http://batch3.phy.bnl.gov:3128;DIRECT"

# Optional but recomended:

# limit how much cache is used on your computer, units in MB
CVMFS_QUOTA_LIMIT=25000

# If not set, some default is chosen (/var/lib/cvmfs/shared).
# Best to put the cache on your fastest disk which has enough space.
CVMFS_CACHE_BASE=/mnt/ssd/cvmfs
#+END_EXAMPLE

Read comments and change example values appropriately.  Refer to CVMFS
documentation for details.

Check if things work:

#+BEGIN_EXAMPLE
# cvmfs_config probe 
Probing /cvmfs/larsoft.opensciencegrid.org... OK
Probing /cvmfs/uboone.opensciencegrid.org... OK
Probing /cvmfs/dune.opensciencegrid.org... OK
#+END_EXAMPLE

