#+title: Singularity Containers for Wire-Cell Toolkit

This repo holds a variety of approaches to leveraging Singularity
containers to provide different environments related to running and
developing the Wire-Cell Toolkit either as stand-alone software or as
run from LArSoft.

The recommended approach is ~wcdo~.  It is "opinionated" in how it is
structured but it also provides hooks for user customization.  For
more info see [[wcdo.org]].

However, before starting be sure you satisfy a these prerequisites:

- [[./singularity.org][singularity]] :: of course this is required.  It is used here to provide a
     bare minimum of Fermilab-supported Scientific Linux OS.

- [[cvmfs.org][cvmfs]] :: to keep the Singularity container file as small and general
     as possible the bulk of software is delivered via the CVMFS
     network file system in the form of UPS binary "products" provided
     by Fermilab.  

- [[./tips.org][tips]] :: some ideas for how to effectively use wcdo, singularity and CVMFS.
